// code-awesome/node-express-angular/webshop/frontend/src/pages/contact..js
import { Component, OnInit } from '@angular/core';

interface ContactData {
  name: string;
  email: string;
  message: string;
}

@Component({
  selector: 'app-contact',
  template: `
    <div class="container">
      <h1>Contact Us</h1>
      <form #contactForm="ngForm" (submit)="onSubmit(contactForm.value)">
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" id="name" class="form-control" [(ngModel)]="name" name="name">
        </div>
        <div class="form-group">
          <label for="email">Email:</label>
          <input type="email" id="email" class="form-control" [(ngModel)]="email" name="email">
        </div>
        <div class="form-group">
          <label for="message">Message:</label>
          <textarea id="message" class="form-control" [(ngModel)]="message" name="message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary" [disabled]="!form.valid">Send</button>
      </form>
    </div>
  `,
  styleUrls: ['./contact.component.css']
})
export class ContactComponent implements OnInit {

  name: string = '';
  email: string = '';
  message: string = '';

  ngOnInit(): void {
  }

  onSubmit(contactForm: ContactData): void {
    console.log('Name:', this.name);
    console.log('Email:', this.email);
    console.log('Message:', this.message);

    // Simulate server-side processing
    const serverResponse = {
      success: true,
      message: 'Thank you for your message!'
    };
    console.log('Server Response:', serverResponse);
  }
}

// code-awesome/node-express-react/webshop2/frontend/src/pages/contact.js
import { useState } from 'react';

const ContactPage = () => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();

    // Simulate sending data to a server
    const serverData = {
      "status": "OK",
      "message": "Your message has been received!"
    };

    console.log("Sending data:", { name, email, message });
    console.log("Server response:", serverData);

    // Reset the form fields
    setName('');
    setEmail('');
    setMessage('');
  };

  return (
    <div className="contact-page">
      <h2>Contact Us</h2>
      <p>Let us know your thoughts!</p>

      <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Name"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <textarea
          placeholder="Message"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
        />
        <button type="submit">Send</button>
      </form>
    </div>
  );
};

export default ContactPage;
