// code-awesome/node-express-angular/webshop/frontend/src/pages/contact..js
import { Component, OnInit } from '@angular/core';

interface ContactData {
  name: string;
  email: string;
  message: string;
}

@Component({
  selector: 'app-contact',
  template: `
    <div class="container">
      <h1>Contact Us</h1>
      <form #contactForm="ngForm" (submit)="onSubmit(contactForm.value)">
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" id="name" class="form-control" [(ngModel)]="name" name="name">
        </div>
        <div class="form-group">
          <label for="email">Email:</label>
          <input type="email" id="email" class="form-control" [(ngModel)]="email" name="email">
        </div>
        <div class="form-group">
          <label for="message">Message:</label>
          <textarea id="message" class="form-control" [(ngModel)]="message" name="message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary" [disabled]="!form.valid">Send</button>
      </form>
    </div>
  `,
  styleUrls: ['./contact.component.css']
})
export class ContactComponent implements OnInit {

  name: string = '';
  email: string = '';
  message: string = '';

  ngOnInit(): void {
  }

  onSubmit(contactForm: ContactData): void {
    console.log('Name:', this.name);
    console.log('Email:', this.email);
    console.log('Message:', this.message);

    // Simulate server-side processing
    const serverResponse = {
      success: true,
      message: 'Thank you for your message!'
    };
    console.log('Server Response:', serverResponse);
  }
}

// code-awesome/python-flask-react/webshop/frontend/src/pages/contact.js
import React, { useState } from 'react';
import axios from 'axios';

const ContactPage = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    message: '',
  });

  const handleChange = (key) => (event) => {
    setFormData({
      ...formData,
      [key]: event.target.value,
    });
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    const data = {
      ...formData,
    };

    try {
      const response = await axios.post('http://localhost:5000/contact', data); // Backend URL
      console.log('Contact form submitted successfully:', response.data);
      alert('Thank you for contacting us!');
      // Optionally reset the form after successful submission
      setFormData({ name: '', email: '', message: '' });
    } catch (error) {
      console.error('Error submitting contact form:', error);
      alert('There was an error submitting the form. Please try again.');
    }
  };

  return (
    <div>
      <h2>Contact Us</h2>
      <p>
        Feel free to reach out to us. We'll get back to you as soon as
        possible.
      </p>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="name">Name:</label>
          <input
            type="text"
            id="name"
            className="form-control"
            placeholder="Your Name"
            value={formData.name}
            onChange={handleChange('name')}
          />
        </div>
        <div className="form-group">
          <label htmlFor="email">Email:</label>
          <input
            type="email"
            id="email"
            className="form-control"
            placeholder="Your Email"
            value={formData.email}
            onChange={handleChange('email')}
          />
        </div>
        <div className="form-group">
          <label htmlFor="message">Message:</label>
          <textarea
            id="message"
            className="form-control"
            placeholder="Your Message"
            value={formData.message}
            onChange={handleChange('message')}
            rows="5"
          />
        </div>
        <button type="submit" className="btn btn-primary">
          Submit
        </button>
      </form>
    </div>
  );
};

export default ContactPage;
