// code-awesome/java-quarkus-angular/voting_app/frontend/src/pages/create-poll.ts
import { Component, OnInit, Input } from '@angular/core';
import { FormControl, Validators } from '@angular/forms';

interface PollOptions {
  title: string;
  description: string;
  options: string[];
}

@Component({
  selector: 'app-create-poll',
  templateUrl: './create-poll.component.html',
  styleUrls: ['./create-poll.component.css']
})
export class CreatePollComponent implements OnInit {

  @Input() pollData: any;

  pollForm = new FormGroup({
    title: new FormControl('', Validators.required),
    description: new FormControl('', Validators.required),
    options: new FormControl([], Validators.required)
  });

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit(): void {
    const title = this.pollForm.value.title;
    const description = this.pollForm.value.description;
    const options = this.pollForm.value.options;

    // You can process the form data here, e.g., send it to the backend.
    console.log('Poll Data:', { title, description, options });

    this.pollForm.reset();
  }

  addOption(): void {
    const options = this.pollForm.value.options || [];
    this.pollForm.value.options = [...options, ''];
  }

  removeOption(index: number): void {
    const options = this.pollForm.value.options || [];
    this.pollForm.value.options = options.filter((_, i) => i !== index);
  }
}

// code-awesome/ruby-on-rails-react/voting_app/frontend/src/pages/create-poll.js
import React, { useState } from 'react';
import { Container, Form, Row, Col, Input, Button } from 'react-bootstrap';

const CreatePollPage = () => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [options, setOptions] = useState('');

  const handleSubmit = (event) => {
    event.preventDefault();
    const optionsArray = options.split('\n');
    const pollData = {
      title: title,
      description: description,
      options: optionsArray,
    };

    // In a real application, you'd send this data to the backend
    console.log('Poll Data:', pollData);

    // Reset the form
    setTitle('');
    setDescription('');
    setOptions('');
  };

  return (
    <Container>
      <h2>Create Poll Page</h2>
      <Form onSubmit={handleSubmit}>
        <Row>
          <Col md={6}>
            <Input
              placeholder="Poll Title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </Col>
          <Col md={6}>
            <Input
              placeholder="Poll Description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </Col>
        </Row>
        <Row>
          <Col md={6}>
            <Input
              placeholder="Option 1"
              value={options}
              onChange={(e) => setOptions(e.target.value)}
            />
          </Col>
          <Col md={6}>
            <Input
              placeholder="Option 2"
              value={options}
              onChange={(e) => setOptions(e.target.value)}
            />
          </Col>
        </Row>
        <Button type="submit" variant="primary">Create Poll</Button>
      </Form>
    </Container>
  );
};

export default CreatePollPage;
