// code-awesome/java-quarkus-angular/mega_ticket/frontend/src/pages/create-event.ts
import { Component, Inject, Input } from '@angular/core';
import { HttpService } from '@angular/http';

@Component({
  selector: 'prg3-create-event',
  template: `
    <h2>Create New Event</h2>

    <form #eventForm="ngForm" (onSubmit)="onSubmit()">

      <div *ngIf="eventErrors">
        <div *ngFor="let error of eventErrors" class="alert alert-danger" role="alert">
          {{ error }}
        </div>
      </div>

      <div>
        <label for="title">Event Title:</label>
        <input type="text" id="title" name="title" placeholder="Event Name" [(ngModel)]="eventData.title" required>
      </div>

      <div>
        <label for="description">Event Description:</label>
        <textarea id="description" name="description" rows="4" cols="50" [(ngModel)]="eventData.description"></textarea>
      </div>

      <div>
        <label for="dateTime">Date & Time:</label>
        <input type="datetime-local" id="dateTime" name="dateTime" [(ngModel)]="eventData.dateTime">
      </div>

      <div>
        <label for="location">Location:</label>
        <input type="text" id="location" name="location" placeholder="Venue" [(ngModel)]="eventData.location">
      </div>

      <div>
        <label for="tickets">Tickets:</label>
        <input type="number" id="tickets" name="tickets" placeholder="Number of Tickets" [(ngModel)]="eventData.tickets" min="1" required>
      </div>

      <button type="submit" [disabled]="eventForm.invalid" >Create Event</button>
    </form>
  `
})
export class CreateEventComponent {
  eventData: any;
  eventErrors: any;

  constructor(private http: HttpService) {
    this.eventData = {
      title: '',
      description: '',
      dateTime: '',
      location: '',
      tickets: 1
    };
    this.eventErrors = [];
  }

  onSubmit() {
    // Validate form input (basic)
    this.eventErrors = [];
    if (!this.eventData.title) {
      this.eventErrors.push('Event title is required');
    }
    if (!this.eventData.description) {
      this.eventErrors.push('Event description is required');
    }
    if (!this.eventData.dateTime) {
      this.eventErrors.push('Date and time is required');
    }
    if (!this.eventData.location) {
      this.eventErrors.push('Location is required');
    }
    if (!this.eventData.tickets) {
      this.eventErrors.push('Tickets must be greater than 0');
    }


    if (this.eventErrors.length === 0) {
      // Send data to the server (simulated)
      this.http.post('/api/events', {
        title: this.eventData.title,
        description: this.eventData.description,
        dateTime: this.eventData.dateTime,
        location: this.eventData.location,
        tickets: this.eventData.tickets
      }).subscribe(
        response => {
          console.log('Event created successfully:', response);
          // Redirect to event page or display success message
        },
        error => {
          console.error('Error creating event:', error);
          // Display error message to the user
        }
      );
    }
  }
}

// code-awesome/python-flask-react/mega_ticket/frontend/src/pages/create-event.js
import React from 'react';
import { useState } from 'react';
import axios from 'axios';

const CreateEvent = () => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [dateTime, setDateTime] = useState('');
  const [location, setLocation] = useState('');
  const [ticketPrice, setTicketPrice] = useState('');
  const [ticketQuantity, setTicketQuantity] = useState('');
  const [eventImage, setEventImage] = useState(''); // Allow event image upload

  const handleSubmit = async (e) => {
    e.preventDefault();

    const eventData = {
      title: title,
      description: description,
      dateTime: dateTime,
      location: location,
      ticketPrice: parseFloat(ticketPrice), // Ensure numeric value
      ticketQuantity: parseInt(ticketQuantity, 10), // Ensure integer value
      eventImage: eventImage,
    };

    try {
      const response = await axios.post('http://localhost:5000/events', {
        eventData: eventData,
      });

      console.log('Event created successfully:', response.data);
      alert('Event created successfully!');
      // Redirect to event page or home page
      window.location.href = '/events/' + response.data.eventId;
    } catch (error) {
      console.error('Error creating event:', error);
      alert('Error creating event. Please check the console for details.');
    }
  };

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setEventImage(reader.result); // Set eventImage to the file's data URL
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <div>
      <h2>Create a New Event</h2>
      <form onSubmit={handleSubmit}>
        <label htmlFor="title">Event Title:</label>
        <input
          type="text"
          id="title"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          required
        />

        <label htmlFor="description">Event Description:</label>
        <textarea
          id="description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows="5"
          required
        />

        <label htmlFor="dateTime">Date and Time:</label>
        <input
          type="datetime-local"
          id="dateTime"
          value={dateTime}
          onChange={(e) => setDateTime(e.target.value)}
          required
        />

        <label htmlFor="location">Location:</label>
        <input
          type="text"
          id="location"
          value={location}
          onChange={(e) => setLocation(e.target.value)}
          required
        />

        <label htmlFor="ticketPrice">Ticket Price:</label>
        <input
          type="number"
          id="ticketPrice"
          value={ticketPrice}
          onChange={(e) => setTicketPrice(e.target.value)}
          step="0.01"
          required
        />

        <label htmlFor="ticketQuantity">Ticket Quantity:</label>
        <input
          type="number"
          id="ticketQuantity"
          value={ticketQuantity}
          onChange={(e) => setTicketQuantity(e.target.value)}
          min="1"
          required
        />

        <label htmlFor="eventImage">Event Image (Optional):</label>
        <input
          type="file"
          id="eventImage"
          accept="image/*"
          onChange={handleImageChange}
        />

        <button type="submit">Create Event</button>
      </form>
    </div>
  );
};

export default CreateEvent;
