// code-awesome/python-flask-react/webshop2/frontend/src/pages/register.js
import React, { useState } from 'react';
import { Link } from '../../frontend/src/components/Navigation';

const register = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!email || !password || !confirmPassword) {
      setError('Please fill in all fields.');
      return;
    }

    if (password !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }

    // Simulate server-side validation and registration
    try {
      const response = await fetch('/api/register', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email, password }),
      });

      if (!response.ok) {
        throw new Error(`Registration failed: ${response.statusText}`);
      }

      // Success - Redirect to login or home
      console.log('Registration successful!');
      // window.location.href = '/login';

    } catch (error) {
      console.error('Registration error:', error);
      setError(error.message || 'An unexpected error occurred during registration.');
    }
  };

  return (
    <div className="register-page">
      <h1>Register</h1>
      <form onSubmit={handleSubmit}>
        <label htmlFor="email">Email:</label>
        <input
          type="email"
          id="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />

        <label htmlFor="password">Password:</label>
        <input
          type="password"
          id="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />

        <label htmlFor="confirmPassword">Confirm Password:</label>
        <input
          type="password"
          id="confirmPassword"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          required
        />

        <button type="submit">Register</button>
        {error && <p style={{ color: 'red' }}>{error}</p>}
      </form>
      <Link to="/login">Already have an account? Login</Link>
    </div>
  );
};

export default register;

// code-awesome/node-express-angular/todo/frontend/src/pages/register.js
// register.js
import { registerUser } from '../../api/user';
import { navigate } from 'svelte/navigation';

const registerForm = document.querySelector('#register-form');
const emailInput = document.getElementById('email');
const passwordInput = document.getElementById('password');
const confirmPasswordInput = document.getElementById('confirm-password');

function validateForm() {
    if (!emailInput.value || !passwordInput.value || !confirmPasswordInput.value) {
        alert('Please fill in all fields.');
        return false;
    }
    if (passwordInput.value !== confirmPasswordInput.value) {
        alert('Passwords must match.');
        return false;
    }

    return true;
}

function handleSubmit() {
    if (!validateForm()) {
        return;
    }

    const user = {
        email: emailInput.value,
        password: passwordInput.value
    };

    registerUser(user)
        .then(() => {
            alert('Registration successful!');
            navigate('/login');
        })
        .catch(error => {
            alert('Registration failed: ' + error.message);
        });
}

if (registerForm) {
    registerForm.addEventListener('submit', handleSubmit);
}
