// code-awesome/python-flask-react/mega_ticket/frontend/src/pages/register.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

const Register = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!email || !password || !confirmPassword) {
      setError('Please fill in all fields.');
      return;
    }

    if (password !== confirmPassword) {
      setError('Passwords must match.');
      return;
    }

    try {
      const response = await axios.post('http://localhost:5000/register', {
        email,
        password,
      });

      if (response.data.success) {
        console.log('Registration successful!');
        navigate('/login'); // Redirect to login page
      } else {
        setError(response.data.error);
      }
    } catch (error) {
      console.error('Registration error:', error);
      setError('Registration failed. Please try again later.');
    }
  };

  return (
    <div className="register-form">
      <h2>Create an Account</h2>
      <form onSubmit={handleSubmit}>
        <label htmlFor="email">Email:</label>
        <input
          type="email"
          id="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />

        <label htmlFor="password">Password:</label>
        <input
          type="password"
          id="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />

        <label htmlFor="confirmPassword">Confirm Password:</label>
        <input
          type="password"
          id="confirmPassword"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          required
        />

        <button type="submit" disabled={error}>Register</button>
        {error && <p className="error-message">{error}</p>}
      </form>
    </div>
  );
};

export default Register;

// code-awesome/node-express-angular/todo/frontend/src/pages/register.js
// register.js
import { registerUser } from '../../api/user';
import { navigate } from 'svelte/navigation';

const registerForm = document.querySelector('#register-form');
const emailInput = document.getElementById('email');
const passwordInput = document.getElementById('password');
const confirmPasswordInput = document.getElementById('confirm-password');

function validateForm() {
    if (!emailInput.value || !passwordInput.value || !confirmPasswordInput.value) {
        alert('Please fill in all fields.');
        return false;
    }
    if (passwordInput.value !== confirmPasswordInput.value) {
        alert('Passwords must match.');
        return false;
    }

    return true;
}

function handleSubmit() {
    if (!validateForm()) {
        return;
    }

    const user = {
        email: emailInput.value,
        password: passwordInput.value
    };

    registerUser(user)
        .then(() => {
            alert('Registration successful!');
            navigate('/login');
        })
        .catch(error => {
            alert('Registration failed: ' + error.message);
        });
}

if (registerForm) {
    registerForm.addEventListener('submit', handleSubmit);
}
