// code-awesome/node-express-react/webshop2/frontend/src/pages/register.js
import React, { useState } from 'react';
import axios from 'axios'; // Assuming axios is installed for API calls
import { Link } from './App'; // Import Link component for navigation

const Register = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!email || !password || !confirmPassword) {
      setError('Please fill in all fields.');
      return;
    }

    if (password !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }

    try {
      const response = await axios.post('/api/register', { // Replace with your API endpoint
        email: email,
        password: password,
      });

      setMessage(response.data.message || 'Registration successful!');
      // Optionally, clear the form after successful registration
      setEmail('');
      setPassword('');
      setConfirmPassword('');
    } catch (error) {
      console.error('Registration error:', error);
      setError('Registration failed. ' + (error.response?.data?.message || 'Check your credentials or try again later.'));
    }
  };

  return (
    <div className="register-page">
      <h1>Register</h1>
      <form onSubmit={handleSubmit}>
        <label htmlFor="email">Email:</label>
        <input
          type="email"
          id="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />

        <label htmlFor="password">Password:</label>
        <input
          type="password"
          id="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />

        <label htmlFor="confirmPassword">Confirm Password:</label>
        <input
          type="password"
          id="confirmPassword"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          required
        />

        <button type="submit">Register</button>
      </form>

      {message && <p>{message}</p>}
      {error && <p className="error">{error}</p>}

      <Link to="/login">Already have an account? Login</Link>
    </div>
  );
};

export default Register;

// code-awesome/node-express-angular/todo/frontend/src/pages/register.js
// register.js
import { registerUser } from '../../api/user';
import { navigate } from 'svelte/navigation';

const registerForm = document.querySelector('#register-form');
const emailInput = document.getElementById('email');
const passwordInput = document.getElementById('password');
const confirmPasswordInput = document.getElementById('confirm-password');

function validateForm() {
    if (!emailInput.value || !passwordInput.value || !confirmPasswordInput.value) {
        alert('Please fill in all fields.');
        return false;
    }
    if (passwordInput.value !== confirmPasswordInput.value) {
        alert('Passwords must match.');
        return false;
    }

    return true;
}

function handleSubmit() {
    if (!validateForm()) {
        return;
    }

    const user = {
        email: emailInput.value,
        password: passwordInput.value
    };

    registerUser(user)
        .then(() => {
            alert('Registration successful!');
            navigate('/login');
        })
        .catch(error => {
            alert('Registration failed: ' + error.message);
        });
}

if (registerForm) {
    registerForm.addEventListener('submit', handleSubmit);
}
